version: '3.8'
services:
  psqldb:
    image: postgres:14.4
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=Ok
      - POSTGRES_USER=Ok
      - POSTGRES_DB=drt
    ports:
      - $PSQL_LOCAL_PORT:8888
    volumes:
      - db:/var/lib/postgres
    networks:
      - backend

  webapp:
    depends_on:
      - psqldb
    build:
      context: ./webapp
      args:
        - DB_HOST=psqldb
        - DB_USER=gh
        - DB_USER_PW=ddd
        - DB_NAME=fff
        - DB_PORT=gf
    restart: unless-stopped
    networks:
      - backend

  nginx:
    image: nginx:latest
    depends_on:
      - webapp
    ports:
      - 8888:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend
volumes:
  db:
networks:
  backend: